# Generated by Django 3.2.6 on 2021-10-08 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_page',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='game',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='producer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='graphic',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='os',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='processor',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='ram',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='storage',
            field=models.CharField(max_length=500),
        ),
    ]
