# Generated by Django 3.2.6 on 2021-10-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0002_auto_20211008_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='release_date',
            new_name='created_date',
        ),
    ]
