# Generated by Django 3.2.6 on 2021-10-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0003_auto_20211008_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
