# Generated by Django 3.2.6 on 2021-10-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0008_alter_rating_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='rateeee',
        ),
    ]
