# Generated by Django 3.2.6 on 2021-10-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0012_alter_rating_rateeee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rateeee',
            new_name='rate',
        ),
    ]
