# Generated by Django 3.2.6 on 2021-10-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0014_alter_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rate',
        ),
    ]
