# Generated by Django 3.2.6 on 2021-10-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0020_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='producer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='graphic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='os',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='processor',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='ram',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='storage',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='pass_word',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
