# Generated by Django 3.2.6 on 2021-10-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0021_auto_20211013_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=None, null=None),
        ),
    ]
