# Generated by Django 3.2.6 on 2021-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0022_alter_game_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(to='gamelib.Category'),
        ),
        migrations.DeleteModel(
            name='Game_Category',
        ),
    ]
