# Generated by Django 3.2.6 on 2021-11-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0023_auto_20211013_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rating', to='gamelib.game'),
        ),
    ]
