# Generated by Django 3.2.6 on 2021-11-06 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0024_alter_rating_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
