# Generated by Django 3.2.6 on 2021-11-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0025_alter_game_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='requirement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='gamelib.requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'game_id')},
        ),
    ]
