# Generated by Django 3.2.6 on 2021-11-11 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0026_auto_20211111_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 20, 24, 50, 451343)),
        ),
    ]
