# Generated by Django 3.2.6 on 2021-11-11 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0028_auto_20211111_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 20, 38, 44, 691091), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 20, 38, 44, 689098), null=True),
        ),
    ]
