# Generated by Django 3.2.6 on 2021-11-12 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelib', '0029_auto_20211111_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 15, 59, 9, 231450), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 15, 59, 9, 231450), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 15, 59, 9, 229451), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user_id', 'game_id')},
        ),
    ]
